git clone https://github.com/ESTOS/kms-cmake-utils -b estos6.3
git clone https://github.com/ESTOS/kurento-module-creator -b estos6.3
git clone https://github.com/ESTOS/gstreamer -b estos6.3
git clone https://github.com/ESTOS/gst-plugins-base -b estos6.3
git clone https://github.com/ESTOS/jsoncpp -b estos6.3
git clone https://github.com/ESTOS/kms-jsonrpc -b estos6.3
git clone https://github.com/ESTOS/libvpx -b estos6.3
git clone https://github.com/ESTOS/kms-core -b estos6.3
git clone https://github.com/ESTOS/libevent -b estos6.3
git clone https://github.com/ESTOS/kurento-media-server -b estos6.3
git clone https://github.com/ESTOS/usrsctp -b estos6.3
git clone https://github.com/ESTOS/openwebrtc-gst-plugins -b estos6.3
git clone https://github.com/ESTOS/libnice -b estos6.3
git clone https://github.com/ESTOS/kms-elements -b estos6.3
git clone https://github.com/ESTOS/opencv -b estos6.3
git clone https://github.com/ESTOS/kms-filters -b estos6.3
git clone https://github.com/ESTOS/gst-plugins-good -b estos6.3
git clone https://github.com/ESTOS/libsrtp -b estos6.3
git clone https://github.com/ESTOS/gst-plugins-bad -b estos6.3
